/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.TrainService;
import org.example.services.UserBookingService;
import org.example.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {
    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        }catch (IOException e){
            System.out.println(e.getMessage());
            return;
        }
        while (option!=7){
            System.out.println("Enter your choice");
            System.out.println("1: SignUp");
            System.out.println("2: Login");
            System.out.println("3: FetchBooking");
            System.out.println("4: Search Trains");
            System.out.println("5: Book a seat");
            System.out.println("6: Cancel my bookings");
            System.out.println("7: Exit");
            Train trainSelectedForBooking = new Train();
            option = scanner.nextInt();
            switch (option){
                case 1:
                    System.out.println("Enter your name");
                    String nameSignup = scanner.next();
                    System.out.println("Enter your password");
                    String passwordSignup = scanner.next();
                    User userSignup = new User(nameSignup, passwordSignup, UserServiceUtil.hashPassword(passwordSignup), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userSignup);
                    break;
                case 2:
//                    login user
                    System.out.println("Enter your name");
                    String nameLogin = scanner.next();
                    System.out.println("Enter your password");
                    String passwordLogin = scanner.next();
                    User userLogin = new User(nameLogin, passwordLogin, UserServiceUtil.hashPassword(passwordLogin), new ArrayList<>(), UUID.randomUUID().toString());
                    try{
                    userBookingService = new UserBookingService(userLogin);
                    } catch (IOException e) {
                        return;
                    }
                    break;
                case 3:
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("Enter source");
                    String source = scanner.next();
                    System.out.println("Enter destination");
                    String dest = scanner.next();
                    List<Train> trains = userBookingService.getTrains(source, dest);
                    int index = 1;
                    for (Train t: trains){
                        System.out.println(index+" Train id : "+t.getTrainId());
                        for (Map.Entry<String, String> entry: t.getStationTimes().entrySet()){
                            System.out.println("station "+entry.getKey()+" time: "+entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3...");
                    trainSelectedForBooking = trains.get(scanner.nextInt());
                    break;
                case 5:
                    System.out.println("Select a seat: ");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for (List<Integer> row: seats){
//                        System.out.print();
                        for (Integer val: row){
                            System.out.print(val+" ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by typing the row and column");
                    System.out.println("Enter the row");
                    int row = scanner.nextInt();
                    System.out.println("Enter the column");
                    int col = scanner.nextInt();
                    System.out.println("Booking your seat....");
                    Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking,row,col);
                    if(booked.equals(Boolean.TRUE)){
                        System.out.println("Booked! Enjoy your journey");
                    }else{
                        System.out.println("Can't book this seat");
                    }
                    break;
                case 6:
                    userBookingService.fetchBooking();
                    System.out.println("Enter Train Id to cancel");
                    String id = scanner.next();
                    try {
                        userBookingService.cancelBooking(id);
                    } catch (IOException e) {
                        return;
                    }
                default:
                    break;
            }
        }
    }
}
